version: '3.4'

services:
  bookipedia:
    container_name: server
    image: bookipedia
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    env_file:
      - .env