version: '3.4'

services:
  bookipedia:
    container_name: bookipedia-debug-container
    image: bookipedia
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    env_file:
      - .env
