name: Deployment

on:

jobs:
  post_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send POST request
        env:
          DEPLOYMENT_KEY: ${{ secrets.DEPLOYMENT_KEY }}
          DEPLOYMENT_URL: ${{ secrets.DEPLOYMENT_URL }}
        run: |
          echo "DEPLOYMENT_URL: $DEPLOYMENT_URL"
          echo "dpf: ${{ env.DEPLOYMENT_URL }}"
          curl -X POST -H "Content-Type: application/json" -d '{"secret_key":"${DEPLOYMENT_KEY}"}' $DEPLOYMENT_URL