name: Docker

on:
  push:
    branches: [ "main", "deploy" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"
          down-flags: "--volumes"
          services: |
            app
      - name: Run docker-compose up
        run: |
          echo VAR1=${{ secrets.VAR1 }} >> .env
          echo VAR2=${{ secrets.VAR2 }} >> .env
          # Add more variables as needed
          docker-compose up