name: Remote Deployment
on:
  push:
    branches: [ "main", "deploy" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install bzip2
      run: sudo apt-get update && sudo apt-get install -y bzip2

    - uses: masterjanic/docker-compose-ssh-deployment@master
      name: Docker-Compose Remote Deployment
      with:
        ssh_host: ${{ secrets.HOST }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_user: ${{ secrets.SSH_USER }}